name: icon-automation
on:
  push:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "install"
      run: yarn install

    - name: Figma Action
      uses: primer/figma-action@v1.0.0-alpha.2
      with:
        args: "format=svg outputDir=./bin/icons/"
      env:
        FIGMA_FILE_URL: "https://www.figma.com/file/${{ secrets.FILE_KEY }}"
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

    - name: "generate"
      run: yarn generate

    - name: "build"
      run: yarn build

    - name: "publish"
      uses: actions/npm@master
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish
